/* istanbul ignore file */
/* tslint:disable */
/* eslint-disable */
import type { ReturnType_typeofJSON_parse_ } from '../models/ReturnType_typeofJSON_parse_';

import type { CancelablePromise } from '../core/CancelablePromise';
import type { BaseHttpRequest } from '../core/BaseHttpRequest';

export class SpecService {

    constructor(public readonly httpRequest: BaseHttpRequest) {}

    /**
     * Gets the generated version of the file at ../../src/tsoa/swagger.json, which should contain a valid open-api v3 spec generated by tsoa.
     * @returns ReturnType_typeofJSON_parse_ The JSON object of the current OAPI spec.
     * @throws ApiError
     */
    public getSpec(): CancelablePromise<ReturnType_typeofJSON_parse_> {
        return this.httpRequest.request({
            method: 'GET',
            url: '/oa-spec.json',
        });
    }

}
