/* istanbul ignore file */
/* tslint:disable */
/* eslint-disable */
import type { ReturnType_typeofJSON_parse_ } from '../models/ReturnType_typeofJSON_parse_';

import type { CancelablePromise } from '../core/CancelablePromise';
import { OpenAPI } from '../core/OpenAPI';
import { request as __request } from '../core/request';

export class SpecService {

    /**
     * Gets the generated version of the file at ../../src/tsoa/swagger.json, which should contain a valid open-api v3 spec generated by tsoa.
     * @returns ReturnType_typeofJSON_parse_ The JSON object of the current OAPI spec.
     * @throws ApiError
     */
    public static getSpec(): CancelablePromise<ReturnType_typeofJSON_parse_> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/oa-spec.json',
        });
    }

}
